image: python:3.7.4-stretch

stages:
  - test
  - deploy

before_script:
  - python3 -m pip install --upgrade pip
  - pip install setuptools wheel twine tox
  - python setup.py sdist


test:
  stage: test
  script:
    - tox

deploy-staging:
  stage: deploy
  when: manual
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_PASSWORD
    TWINE_REPOSITORY_URL: $TEST_PYPI_REPOSITORY_URL
  script:
    #- rename "s/$(python setup.py --version)/$(python setup.py --version).dev$CI_BUILD_ID/" dist/*.tar.gz
    #- twine upload --verbose dist/$(python setup.py --name)-$(python setup.py --version).dev$CI_BUILD_ID.tar.gz
    - twine upload --verbose dist/*
  only:
    - develop
    - master

deploy-prod:
  stage: deploy
  when: manual
  variables:
    TWINE_USERNAME: $PROD_USERNAME
    TWINE_PASSWORD: $PROD_PASSWORD
    TWINE_REPOSITORY_URL: $TEST_PYPI_REPOSITORY_URL
  script:
    - twine upload --verbose dist/*
  only:
    - tags
